# Generated by Django 4.2.1 on 2023-06-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postinteraction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postinteraction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='post-user post interaction unique'),
        ),
    ]
