# Generated by Django 4.2.1 on 2023-06-04 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_alter_postinteraction_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostInteraction',
            new_name='PostVote',
        ),
    ]
